pre-commit:
  parallel: true
  commands:
    golangci-lint:
      glob: "*.go"
      run: golangci-lint run --fix --new-from-rev HEAD~1
      stage_fixed: true
    go-mod-tidy:
      glob: "go.mod"
      run: go mod tidy && git add go.mod go.sum
    gitleaks:
      run: gitleaks git --staged --no-banner --redact -v